In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_excel('exoplanetss.xlsx')
df['lum_watt'] = df['st_lum']*(3.826*10**26) # converting solar luminosities to watts
df['semi_major_meters'] = df['pl_orbsmax']*(1.496*10**11) # converting au to meters
df

,Unnamed: 0,Unnamed: 1,discoverymethod,pl_orbsmax,pl_bmasse,pl_orbeccen,st_teff,st_rad,st_mass,st_lum,st_logg,sy_dist,lum_watt,semi_major_meters
0,NaN,NaN,Radial Velocity,1.210,5434.70000,NaN,NaN,NaN,2.60,NaN,NaN,93.1846,NaN,1.810160e+11
1,NaN,NaN,Radial Velocity,1.290,6165.60000,0.231,4742.0,19.00,2.70,2.243,2.31,93.1846,8.581718e+26,1.929840e+11
2,NaN,NaN,Radial Velocity,1.178,4914.89849,0.238,4874.0,13.76,2.09,1.978,2.45,93.1846,7.567828e+26,1.762288e+11
3,NaN,NaN,Radial Velocity,1.530,4684.81420,0.080,4213.0,29.79,2.78,NaN,1.93,125.3210,NaN,2.288880e+11
4,NaN,NaN,Radial Velocity,1.510,3432.40000,NaN,NaN,NaN,1.70,NaN,NaN,125.3210,NaN,2.258960e+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36139,ups And d,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36140,ups Leo b,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36141,xi Aql b,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36142,xi Aql b,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36143,xi Aql b,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
pi = 3.14159265359
df['is_terrestrial'] = np.where(df['st_logg'] < 9.8, 1, 0)# compares planet's surface gravity to that of Earth
flux = df['lum_watt']*(1-0.2)  #0.2 is taken as albedo here due to its value being slightly lower than Earth's (0.3) 
denom = 16*pi*df['semi_major_meters']**2*((1 - df['pl_orbeccen']**2)**0.5)
df['flux']= flux/denom

In [3]:
rows = df[(df['flux']>=65) & (df['flux']<=300)].copy()
rows['habitability_index'] = rows['flux']*rows['is_terrestrial']
rows

,Unnamed: 0,Unnamed: 1,discoverymethod,pl_orbsmax,pl_bmasse,pl_orbeccen,st_teff,st_rad,st_mass,st_lum,st_logg,sy_dist,lum_watt,semi_major_meters,is_terrestrial,flux,habitability_index
23,11 UMi b,1,Radial Velocity,1.450,1373.01872,0.0600,4157.00,25.92,1.22,2.254,1.70,124.9530,8.623804e+26,2.169200e+11,1,292.215305,292.215305
25,14 And b,1,Radial Velocity,2.476,2926.24614,0.0240,4980.00,8.80,2.10,1.634,2.87,76.2220,6.251684e+26,3.704096e+11,1,72.540041,72.540041
33,14 Her b,2,Radial Velocity,1.333,632.46000,0.0900,5098.00,4.90,1.54,1.164,3.50,72.0691,4.453464e+26,1.994168e+11,1,178.961927,178.961927
34,14 Her b,2,Radial Velocity,2.080,273.32000,0.2900,5098.00,4.90,1.54,1.164,3.50,72.0691,4.453464e+26,3.111680e+11,1,76.489917,76.489917
130,55 Cnc e,5,Radial Velocity,2.200,762.80000,0.1340,4978.00,5.20,1.70,1.176,3.16,54.6599,4.499376e+26,3.291200e+11,1,66.711145,66.711145
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36063,iot Dra c,2,Radial Velocity,1.790,7057.73298,0.1240,4886.00,14.60,2.70,2.039,2.56,46.2107,7.801214e+26,2.677840e+11,1,174.492942,174.492942
36064,kap And b,1,Radial Velocity,1.765,6848.56651,0.1260,4887.00,12.24,2.61,1.895,2.64,46.2107,7.250270e+26,2.640440e+11,1,166.838699,166.838699
36065,kap And b,1,Radial Velocity,1.900,7627.92000,0.1256,4928.00,15.10,3.04,2.090,NaN,46.2107,7.996340e+26,2.842400e+11,0,158.779298,0.000000
36090,omi CrB b,1,Radial Velocity,0.827,21.60000,0.0000,5817.00,1.34,0.95,0.260,4.25,17.4671,9.947600e+25,1.237192e+11,1,103.434219,103.434219
36115,tau Cet e,4,Radial Velocity,0.832,610.23360,0.2240,6105.51,1.64,1.15,0.525,4.07,13.4054,2.008650e+26,1.244672e+11,1,211.735165,211.735165

In [1]:
plt.scatter(rows['habitability_index'], rows['sy_dist'],marker='.', c=rows['habitability_index'], cmap='magma')
plt.colorbar(label='Habitability Index')
plt.xlabel('Habitability index')
plt.ylabel('Distance/pc')
plt.title('Habitability of Exoplanets')
plt.show()

NameError: name 'plt' is not defined